export const Products = [
    {
        id: 12,
        model: "Office_365",
        name: 'Office 365 subscription',
        photo: "../../assets/images/products/12.jpg",
        desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        full_desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        price: "460.65"
    },
    {
        id: 13,
        model: "Windows 10",
        name: 'WINDOWS 10 subscription',
        photo: "../../assets/images/products/13.jpg",
        desc: "Windows 10 is a personal computer operating system developed and released by Microsoft as part of the Windows NT family of operating systems. It was first released on July 29, 2015.[7] Unlike previous versions of Windows, Microsoft has branded Windows 10 as a service that receives ongoing Devices in enterprise environments can receive these updates at a slower pace, or use long-term support milestones that only receive critical updates, such as security patches, over their ten-year lifespan of extended support",
        full_desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        price: "460.65"
    },
    {
        id: 12,
        model: "Office_365",
        name: 'Office 365 subscription',
        photo: "../../assets/images/products/12.jpg",
        desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        full_desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        price: "460.65"
    },
    {
        id: 12,
        model: "Office_365",
        name: 'Office 365 subscription',
        photo: "../../assets/images/products/12.jpg",
        desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        full_desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        price: "460.65"
    }
];