export const Products = [
    {
        id: 12,
        model: "Office_365",
        name: 'Office 365 subscription',
        photo: "../../assets/images/products/12.jpg",
        desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        full_desc: "Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.Office 365 Home Office 365 Home Not yet rated ₹ 4,619.00 per year ₹ 460.00 per monthShop now Best for households. Includes always up-to-date Office applications and extra OneDrive storage for up to 5 users.",
        price: "460.65"
    }
];